### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by hend0298** [hend0298/hero-banner#1]
@thomasjbradley I can't figure out how to make the h2 go closer to the top but not be super far from the paragraph.

**Comment by thomasjbradley** [comment]
In the CSS, for `.content`, there’s both `top` & `bottom`. If you remove the `top` it moves down. It’s not always a good idea to use the top & bottom properties at the same time. It’s telling the element to got to the top & also go to the bottom of its parent—at the same time.

**Comment by hend0298** [comment]
@thomasjbradley Okay, I fixed that so now there's just too much space in between the h2 and the paragraph. How do I get them closer?

**Comment by thomasjbradley** [comment]
Adjust the margins on the `<p>` tag?

**Comment by hend0298** [comment]
@thomasjbradley How do I get the space on top of the h2 if it's inline?

**Comment by thomasjbradley** [comment]
I can’t say exactly because it looks like the code hasn’t been pushed. But instead of having `bottom: 0` try something like `bottom: .5em`.
